export { getPool, query, queryOne, queryMany, closePool } from "./db/client.js";
export * from "./db/offers.js";
export * from "./db/campaigns.js";
export * from "./db/companies.js";
export * from "./db/contacts.js";
export * from "./db/campaign-contacts.js";
export * from "./db/messages.js";
export * from "./db/tool-usage.js";
export * from "./db/signal-routing-audit.js";

export type { Offer, CreateOfferInput, UpdateOfferInput, ICP, CompanyProfile, BuyerProfile, ScoringRubric, PositioningCanvas } from "./types/offer.js";
export type { Campaign, CampaignWithOffer, CreateCampaignInput, UpdateCampaignInput, SignalConfig, SignalType, CampaignStatus, MessagingFramework } from "./types/campaign.js";
export type { Company, UpsertCompanyInput, SignalData } from "./types/company.js";
export type { Contact, UpsertContactInput, CampaignContact, CampaignContactWithDetails, Seniority, CampaignContactStatus } from "./types/contact.js";
export type { Message, CreateMessageInput, UpdateMessageInput, Channel, MessageStatus, ReplySentiment } from "./types/message.js";
export type { ToolUsage, LogToolUsageInput, AccountActivity, LogActivityInput } from "./types/api.js";
export type { SignalRoutingAudit, LogSignalRoutingAuditInput, SignalRoutingDecision } from "./types/signal-routing.js";
export { SIGNAL_TYPES, CAMPAIGN_STATUSES, MESSAGING_FRAMEWORKS } from "./types/campaign.js";
export { SENIORITY_LEVELS, CAMPAIGN_CONTACT_STATUSES } from "./types/contact.js";
export { CHANNELS, MESSAGE_STATUSES, REPLY_SENTIMENTS } from "./types/message.js";
export { DAILY_LIMITS } from "./types/api.js";
export { SIGNAL_ROUTING_DECISIONS } from "./types/signal-routing.js";
